In [1]:
import pandas as pd
from sklearn import preprocessing

In [3]:
df= pd.read_csv("train_6개버젼.csv", encoding='cp949')
df2 = pd.read_csv("test_6개버젼.csv", encoding='cp949')

In [5]:
df.columns

Index(['계좌 ID', '종목코드', '매수일자', '보유기간(일)', 'oil_14_0.8', 'oil_7_0.8',
       'oil_3_0.8', 'oil_14_0.6', 'oil_7_0.6', 'oil_3_0.6', 'copper_14_0.8',
       'copper_7_0.8', 'copper_3_0.8', 'copper_14_0.6', 'copper_7_0.6',
       'copper_3_0.6', 'base_14_0.8', 'base_7_0.8', 'base_3_0.8',
       'base_14_0.6', 'base_7_0.6', 'base_3_0.6', 'exchange_14_0.8',
       'exchange_7_0.8', 'exchange_3_0.8', 'exchange_14_0.6', 'exchange_7_0.6',
       'exchange_3_0.6', 'Rank'],
      dtype='object')

In [6]:
x = df[['oil_14_0.8', 'oil_7_0.8',
       'oil_3_0.8', 'oil_14_0.6', 'oil_7_0.6', 'oil_3_0.6', 'copper_14_0.8',
       'copper_7_0.8', 'copper_3_0.8', 'copper_14_0.6', 'copper_7_0.6',
       'copper_3_0.6', 'base_14_0.8', 'base_7_0.8', 'base_3_0.8',
       'base_14_0.6', 'base_7_0.6', 'base_3_0.6', 'exchange_14_0.8',
       'exchange_7_0.8', 'exchange_3_0.8', 'exchange_14_0.6', 'exchange_7_0.6',
       'exchange_3_0.6']].values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
scaled = pd.DataFrame(x_scaled)

In [7]:
scaled

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.931539,0.931539,0.931182,0.925416,0.925416,0.922951,0.532362,0.532362,0.532494,0.52777,...,0.8,0.8,0.8,0.8,0.357053,0.357053,0.357026,0.357937,0.357930,0.356500
1,0.931539,0.931539,0.931182,0.925416,0.925416,0.922951,0.532362,0.532362,0.532494,0.52777,...,0.8,0.8,0.8,0.8,0.357053,0.357053,0.357026,0.357937,0.357930,0.356500
2,0.931539,0.931539,0.931182,0.925416,0.925416,0.922951,0.532362,0.532362,0.532494,0.52777,...,0.8,0.8,0.8,0.8,0.357053,0.357053,0.357026,0.357937,0.357930,0.356500
3,0.931539,0.931539,0.931182,0.925416,0.925416,0.922951,0.532362,0.532362,0.532494,0.52777,...,0.8,0.8,0.8,0.8,0.357053,0.357053,0.357026,0.357937,0.357930,0.356500
4,0.931539,0.931539,0.931182,0.925416,0.925416,0.922951,0.532362,0.532362,0.532494,0.52777,...,0.8,0.8,0.8,0.8,0.357053,0.357053,0.357026,0.357937,0.357930,0.356500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681467,0.839770,0.839770,0.839556,0.821307,0.821417,0.820437,0.552473,0.552473,0.552076,0.55745,...,1.0,1.0,1.0,1.0,0.355557,0.355557,0.355298,0.354834,0.354828,0.351462
681468,0.839770,0.839770,0.839556,0.821307,0.821417,0.820437,0.552473,0.552473,0.552076,0.55745,...,1.0,1.0,1.0,1.0,0.355557,0.355557,0.355298,0.354834,0.354828,0.351462
681469,0.839770,0.839770,0.839556,0.821307,0.821417,0.820437,0.552473,0.552473,0.552076,0.55745,...,1.0,1.0,1.0,1.0,0.355557,0.355557,0.355298,0.354834,0.354828,0.351462
681470,0.839770,0.839770,0.839556,0.821307,0.821417,0.820437,0.552473,0.552473,0.552076,0.55745,...,1.0,1.0,1.0,1.0,0.355557,0.355557,0.355298,0.354834,0.354828,0.351462
681471,0.839770,0.839770,0.839556,0.821307,0.821417,0.820437,0.552473,0.552473,0.552076,0.55745,...,1.0,1.0,1.0,1.0,0.355557,0.355557,0.355298,0.354834,0.354828,0.351462

In [9]:
scaled.columns=['oil_14_0.8', 'oil_7_0.8',
       'oil_3_0.8', 'oil_14_0.6', 'oil_7_0.6', 'oil_3_0.6', 'copper_14_0.8',
       'copper_7_0.8', 'copper_3_0.8', 'copper_14_0.6', 'copper_7_0.6',
       'copper_3_0.6', 'base_14_0.8', 'base_7_0.8', 'base_3_0.8',
       'base_14_0.6', 'base_7_0.6', 'base_3_0.6', 'exchange_14_0.8',
       'exchange_7_0.8', 'exchange_3_0.8', 'exchange_14_0.6', 'exchange_7_0.6',
       'exchange_3_0.6']

In [11]:
train_scaled = pd.concat([df[['계좌 ID', '종목코드','매수일자','보유기간(일)','Rank']], scaled],axis=1)

In [13]:
train_scaled.head(1)

,계좌 ID,종목코드,매수일자,보유기간(일),Rank,oil_14_0.8,oil_7_0.8,oil_3_0.8,oil_14_0.6,oil_7_0.6,...,base_3_0.8,base_14_0.6,base_7_0.6,base_3_0.6,exchange_14_0.8,exchange_7_0.8,exchange_3_0.8,exchange_14_0.6,exchange_7_0.6,exchange_3_0.6
0,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A006360,2018-07-26,11,75.0,0.931539,0.931539,0.931182,0.925416,0.925416,...,0.8,0.8,0.8,0.8,0.357053,0.357053,0.357026,0.357937,0.35793,0.3565